### PR TITLE
Update cloudflare go to the latest version

### PR DESCRIPTION
**Pull request by A2va**

### CODE REVIEW

**Comment by justmiles** [comment]
Hey @A2va thank you for this. I'll test next week and get it merged!

**Comment by A2va** [comment]
Hi @justmiles ! Did you find the time to test it ?

**Comment by justmiles** [comment]
Hey, @A2va, haven't gotten to it yet but will try too soon.

**Comment by justmiles** [comment]
Thanks, @A2va - this looks great!

**Comment by justmiles** [comment]
This is available in [v0.1.5](https://github.com/justmiles/traefik-cloudflare-tunnel/releases/v0.1.5)

**Pull request merged**
